blank_issues_enabled: false
contact_links:
  - name: Questions, Sharing ideas, Other support
    url: https://github.com/meza/minecraft-mod-manage/discussions
    about: Check out the community discussions.
